name: CI
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: purcell/setup-emacs@v3.0
      with:
       version: 24.5
    - uses: actions/checkout@v2
    - name: check version
      run: |
       emacs --version
    - name: emacs help
      run: |
       emacs --help
    - name: emacs processing
      run: |
       cd scripts && emacs --batch -Q --load packages.el
