name: CI
on:
  push:
    branches: [org-to-html]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: purcell/setup-emacs@v3.0
      with:
       version: 24.5
    - uses: actions/checkout@v2
    - name: check version
      run: |
       emacs --version
    - name: emacs help
      run: |
       emacs --help
    - name: emacs processing
      run: |
       emacs coding-with-emacs.org --batch -Q -f org-html-export-to-html --kill
#    - name: deploy
#      uses: peaceiris/actions-gh-pages@v3
#      with:
#       github_token: ${{ secrets.GITHUB_TOKEN }}
#       publish_dir: ./html
